# ZED2

#==============#
# Camera Model #
#==============#

Camera:
  name: "ZED2"
  setup: "stereo"
  model: "perspective"

  fx: 522.6021728515625
  fy: 522.6021728515625
  cx: 650.2871704101562
  cy: 359.57666015625

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  fps: 15.0
  cols: 1280
  rows: 720
  focal_x_baseline: 62.71224 # 522.602 * 0.12
  depth_threshold: 40

  color_order: "Gray"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  max_num_keypoints: 2000
  ini_max_num_keypoints: 4000

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 12
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9

#========================#
# Initializer Parameters #
#========================#

Initializer:
  num_min_triangulated_pts: 100

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 1.2
  keyframe_line_width: 1
  graph_line_width: 2
  point_size: 2
  camera_size: 0.8
  camera_line_width: 3
  viewpoint_x: 0.0
  viewpoint_y: -300
  viewpoint_z: -0.1
  viewpoint_f: 2800
